export const REMOVE_SINGLE_INDEX = 'REMOVE_SINGLE_INDEX'
export const UPDATE_INDEX = 'UPDATE_INDEX'
export const UPDATE_SINGLE_INDEX = 'UPDATE_SINGLE_INDEX'

export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'
export const SET_ALBUM = 'SET_ALBUM'
